######### DEFAULT #########

spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/lokumcubaba?serverTimezone=UTC
    username: root
    password: mustafa1
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

